### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ankithans** [comment]
we don't have any self assessment tests till now in the application.

**Comment by ghost** [comment]
I am working on it!
It will be added within a hour

Thanks and regards,
Kurubaran Anandhan.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by ankithans** [comment]
Ok that's great!

**Comment by ghost** [comment]
Made a pull request please check and merge ...Added Screenshots for self assessment test.https://github.com/ankithans/Covid-19-Tracker/pull/6https://github.com/ankithans/Covid-19-Tracker/pull/7On 11-Jul-2020 4:37 pm, Ankit Hans <notifications@github.com> wrote:
Ok that's great!

**Pull request merged**
