### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by tushar821999**
Fix Screenshots display in readme.md

### CODE REVIEW

**Review by tushar821999 — COMMENTED** [review]
Images Display Properly Now

**Comment by ankithans** [comment]
@tushar821999 Thanks for contributing to this project. 
A small fix to be done so that I can merge this pull request.
image

Here 3 images should be in a row that will look great!

**Comment by tushar821999** [comment]
grid

**Comment by ankithans** [comment]
Great job @tushar821999 . Again thanks for your valuable contribution.

**Pull request merged**
